import Head from "next/head";
import Footer from "./Footer";
import NavBar from "./NavBar";
import { Poppins } from "@next/font/google";
import { dataContext } from "../utils/dataContext";
import { useState } from "react";

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["devanagari"],
});

function Layout({ children }) {
  const [showModal, setshowModal] = useState(false);
  const [uploadImage, setUploadImage] = useState();
  const [preview, setPreview] = useState("");

  const component = (
    <dataContext.Provider
      value={{
        showModal,
        setshowModal,
        uploadImage,
        setUploadImage,
        preview,
        setPreview,
      }}
    >
      <div className={poppins.className}>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <NavBar />

        {children}

        <Footer />
      </div>
    </dataContext.Provider>
  );

  return component;
}

export default Layout;
